# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB=post_db 
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=user123

# Expose the PostgreSQL port
EXPOSE 5432